# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: DCSys add-on
version: "1.0.0"
slug: example
description: DCSys add-on
url: "https://github.com/Jorre05/dcsys_ha_addon"
arch:
  - aarch64
init: false
map:
  - share:rw
options:
  message: "Hello DCSys..."
schema:
  message: "str?"
image: "ghcr.io/home-assistant/{arch}-addon-example"
